name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        php-versions: ["7.0", "7.4", "8.0", "8.2"]

    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php-versions }} Test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, simplexml
          coverage: xdebug

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: PHPUnit
        run: vendor/bin/phpunit

      - name: Upload coverage results to Coveralls
        if: ${{ matrix.php-versions }} != '7.0'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=coverage/clover.xml --json_path=coverage/coveralls-upload.json -v
